export const PERMISSION_NAME = {
  ADD_UNIVERSITY: "ADD_UNIVERSITY",
  VIEW_UNIVERSITY: "VIEW_UNIVERSITY",
  UPDATE_UNIVERSITY: "UPDATE_UNIVERSITY",
  DELETE_UNIVERSITY: "DELETE_UNIVERSITY",
};
export const PERMISSION_GROUP = {
  UNIVERSITY: "UNIVERSITY",
};
