module.exports = {
  ACTIVE: "Active",
  PENDING: "Pending",
  INACTIVE: "Inactive",
  LOCKED: "Locked",
  SALT_ROUNDS: 10,
  OTP_EXPIRE: 5,
  SUCCESS: "success",
  FAILURE: "failure",
  SERVER_ERROR_MESSAGE: "Internal server error",
  STATUS: {
    ACTIVE: "Active",
    HOLD: "Hold",
    SUSPENDED: "Suspended",
    INACTIVE: "Inactive",
    EXPIRED: "Expired",
  },
  RESOURCES: {},
  PERMS: {},
};
